var a: int
var b:int=1
var c :int=-2

var abc: int = -1- 2 + 3+4

a:= -5

a :=- 4

var f: float = 5.1

f= -4.2345

fun myFunction(b: int): int {
    var a: int
    a = 1 * 4 - 5 * (b +1)
}

{
    if a + b < 7 {
        c:= c+a +3
        a :=-b-c+a+4
    }

    var i: int = 1
    while i <5 {
        f:= f + 1
        c := c*2
        b :=a +(a- b)
    }

    f = f * 3 / 2

    {{}}

        $&&$&$&

        { { } }
        {  {}}

    _PRINTVARTABLE
}